### ISSUE TITLE
Contact Form Validation

### ISSUE THREAD

**Issue by evocate** [AberdeenPHP/AberdeenPHP-Website#49]
https://github.com/AberdeenPHP/AberdeenPHP-Website/blob/c5652cb5510fa0350b3b358940108b9701c8ac00/app/Http/Requests/ContactFormRequest.php#L24-L32

Apart from wanting an excuse for using the linking of code directly into an issue that I learned from the latest meetup...  _fist pump #aberdeenphp_

Is there a reason a name can't have two characters and should there be a sensible limit on how many characters can be used for the user's name and message?

**Comment by sunscreem** [comment]
I do this because in my experience the only people who don't put their full name into a form are spammers :( Especially the non-bot type spammers - usually trying to sell you dodgy SEO stuff.

For the max length - there's no reason why you couldn't add that if you like (it would need to be on the front and back end) but it's not really needed. Happy to merge a PR if you want to clock up some more open source 'points' though :)

**Comment by evocate** [comment]
Poor Jo.  

You know my game  ;-)  Should there be a character limit for the message itself, if so what do you suggest?  Or just the name itself?

**Comment by sunscreem** [comment]
I'd say a name should never be more than 100 chars.

And a message about 5000?

**Comment by evocate** [comment]
a4c8cae676e940935988ef04d188eabfffbf584d
